### ISSUE TITLE
Unable to list providers 

### ISSUE THREAD

**Issue by jcandresen** [excludarr/excludarr#23]
**Describe the bug**  
When attempting to list providers using the command `excludarr --debug providers list`, the application fails with a `TypeError` indicating that the `Retry.__init__()` method received an unexpected keyword argument `method_whitelist`. This error occurs even though the configuration file seems correctly set up.

**To Reproduce**  
1. Execute the command: 
   ```bash
   excludarr --debug providers list
   ```
2. The error occurs regardless of the movie or series being processed since it happens during the provider listing.
3. The configuration file used is as follows (sensitive data has been removed):

   ```yaml
   general:
     locale: 'en_CA'
   providers:
     - 'netflix'
     - 'amazon prime video'
   radarr:
     url: 'http://192.168.0.75:37878'
     api_key: '<REDACTED>'
     verify_ssl: false
     exclude_tags: []
   sonarr:
     url: 'http://192.168.0.75:38989'
     api_key: '<REDACTED>'
     verify_ssl: false
     exclude: []
   ```

**Expected behavior**  
I expected the command to successfully list the available providers without errors.

**Versions**  
1. OS Version: Debian 11  
2. Excludarr version: v1.0.7  
3. Python version: 3.11  

**Debug logging**  
![image](https://github.com/user-attachments/assets/69c7b714-3ae8-4f78-8583-0275fb72e3ab)
