### ISSUE TITLE
Sonarr Not-Monitored action don't work for whole series

### ISSUE THREAD

**Issue by bayramog** [excludarr/excludarr#26]
**Describe the bug**
Hello! I am using excludarr with not-monitored action on my sonarr instance. I have one example series to describe my situation which is Actress (2023) {tvdb-423009}. This series is under Ended status and has only one season. Also it is available under Disney+ in my country TR. When excludarr run it does not make series itself unmonitored but only the season itself. 

**To Reproduce**
1. Add the series Actress (2023) {tvdb-423009} as unmonitored on Sonarr
2. Add Disney+ to excludarr configuration to exclude Disney+ series.
3. Run Excludarr command like this excludarr sonarr exclude -a not-monitored -d -e -y
4. My docker-compose and crontab files at below.

Docker Compose:
```
services:
  excludarr:
    image: excludarr/excludarr
    container_name: excludarr
    restart: unless-stopped
    environment:
      - GENERAL_FAST_SEARCH=true
      - GENERAL_LOCALE=TR
      - GENERAL_PROVIDERS=netflix, amazon prime video, disney plus
      - RADARR_URL=REDACTED
      - RADARR_API_KEY=REDACTED
      - RADARR_VERIFY_SSL=false
      - SONARR_URL=REDACTED
      - SONARR_API_KEY=REDACTED
      - SONARR_VERIFY_SSL=false
      - CRON_MODE=true
    volumes:
      - /mnt/.ix-apps/app_configs/excludarr/crontab:/etc/excludarr/crontab
```

Crontab file:

```
# minute    hour    day   month   weekday   command
25          *       *     *       *         excludarr sonarr exclude -a not-monitored -d -e -y
40          *       *     *       *         excludarr radarr exclude -a not-monitored -d -e -y
55          *       *     *       *         excludarr sonarr re-add -y
10          *       *     *       *         excludarr radarr re-add -y
35          *       *     *       *         excludarr sonarr exclude -a not-monitored -d -e -y
30          *       *     *       *         excludarr radarr exclude -a not-monitored -d -e -y
45          *       *     *       *         excludarr sonarr exclude -a not-monitored -d -e -y
50          *       *     *       *         excludarr radarr exclude -a not-monitored -d -e -y
0           *       *     *       *         excludarr sonarr exclude -a not-monitored -d -e -y
5           *       *     *       *         excludarr radarr exclude -a not-monitored -d -e -y
15          *       *     *       *         excludarr sonarr exclude -a not-monitored -d -e -y
20          *       *     *       *         excludarr radarr exclude -a not-monitored -d -e -y
```
 

**Expected behavior✱
Normally since the series has below status, I am expecting not only season also entire show is beingalso mark as unmonitored by Exludarr
- It is ended show
- It has one season and the season is included in Disney+

✱Versions✱
1. OS Version: Docker on TrueNAS
2. Excludarr version: v.1.1.3
3. Python version: v3.11.9 inside docker

**Debug logging✱
To debug the problem further, we need to know exactly what went wrong. Therefor we ask you to run the command in debug mode. You can achieve this by appending the `--debug` flag after the base command `excludarr`. e.g. `excludarr --debug sonarr exclude -a delete -d -e`.

If the output is too long, please paste the output to pastebin or github gist and link it in this issue.

Link for logs: https://gist.github.com/bayramog/46da6748c0a1a3ea60dbff1a464018b8.js

**Additional context✱
